INSERT INTO category(category_name, category_img)
VALUES (N'Polo', 'https://360.com.vn/wp-content/uploads/2023/06/Aso-polo.webp')
INSERT INTO category(category_name, category_img)
VALUES (N'Áo Phông', 'https://360.com.vn/wp-content/uploads/2023/02/Ao-phong.png')
INSERT INTO category(category_name, category_img)
VALUES (N'Sơ Mi', 'https://360.com.vn/wp-content/uploads/2023/01/anh6.webp')
INSERT INTO category(category_name, category_img)
VALUES (N'Blazer', 'https://360.com.vn/wp-content/uploads/2023/01/anh4.webp')
INSERT INTO category(category_name, category_img)
VALUES (N'Quần Jogger', 'https://360.com.vn/wp-content/uploads/2023/01/anh8.webp')
INSERT INTO category(category_name, category_img)
VALUES (N'Quần Kaki', 'https://360.com.vn/wp-content/uploads/2023/11/QKLTK402-8-Custom.png')
INSERT INTO category(category_name, category_img)
VALUES (N'Quần Jeans', 'https://360.com.vn/wp-content/uploads/2023/01/anh7.webp')
INSERT INTO category(category_name, category_img)
VALUES (N'Quần Âu', 'https://360.com.vn/wp-content/uploads/2023/06/Quan-au.webp')